apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-inference
spec:
  rules:
    - host: cv-inference.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-inference
                port:
                  number: 80
